### PR TITLE
update faraday to 1.0

### PR DESCRIPTION
**Pull request by d-m-u**
middleware got cut over the weekend so we should be able to do this now

### CODE REVIEW

**Comment by d-m-u** [comment]
@bdunne please review

**Comment by bdunne** [comment]
Cool!  Can you run a cross-repo test?

**Comment by d-m-u** [comment]
sorry, i need https://github.com/ManageIQ/manageiq-providers-azure_stack/pull/28 in first then we can try this again

**Comment by d-m-u** [comment]
https://github.com/ManageIQ/manageiq-cross_repo-tests/pull/104

**Comment by chessbyte** [comment]
@bdunne @Fryguy @d-m-u is this close to the finish line?

**Pull request merged**
