### PR TITLE
Switch to GitHub Actions

### PR DESCRIPTION
**Pull request by Fryguy**
CI: https://github.com/Fryguy/manageiq-api-client/actions?query=branch%3Agithub_actions

### CODE REVIEW

**Comment by agrare** [comment]
@Fryguy looks like a number of failures but none of them consistent, guessing the logger spec failure is sporadic

**Comment by Fryguy** [comment]
@agrare Thanks...I usually try to double check this is green before pinging you so, sorry for that

**Comment by Fryguy** [comment]
It's a sporadic test failure...  I added in order random, and it's showing up...I'll pull out for now and do a follow up.

**Comment by Fryguy** [comment]
Actually, it was easier to just fix...this should be good to go.

**Review by agrare — APPROVED** [review]

**Pull request merged**
